language: node_js
node_js:
- node
install:
- npm install
- cd functions && npm install && cd ..
script:
- npm run apidoc
- if [ "$TRAVIS_BRANCH" == "master" ]; then npm run deploy; fi
notifications:
  email: false
