subscription DeviceStreamMarkAdded ($deviceIds: [ID!]!) {
  deviceStreamMarkAdded (deviceIds: $deviceIds) {
    sequence
    tally
    mark
    info {
      competitionEventId
      rulesId
      judgeType
    }
    device { id }
  }
}
