query HeatEntriesScoresheets ($groupId: ID!, $heat: Int!) {
  group (groupId: $groupId) {
    id
    entriesByHeat (heat: $heat) {
      ...EntryFragment
      scoresheets {
        ...ScoresheetBaseFragment
        ...MarkScoresheetFragment
        ...TallyScoresheetFragment
      }
    }
  }
}
