query HeatEntriesScoresheets ($groupId: ID!, $heat: Int!) {
  group (groupId: $groupId) {
    id
    entriesByHeat (heat: $heat) {
      ...FullEntry
      scoresheets {
        ...BaseScoresheet
      }
    }
  }
}
