name: QA

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - run: npm ci --prefer-offline
      - run: npm run codegen
      - run: npm run lint
      - run: npm run typecheck
